.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pull 1  "pull "
.SH NAME
pull \- Fetch from and integrate with another repository
.SH SYNOPSIS
\fBpull\fR [\fB\-\-rebase\fR] [\fB\-\-no\-ff\fR] [\fB\-\-squash\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIREMOTE\fR] [\fIBRANCH\fR]
.SH DESCRIPTION
Fetch from and integrate with another repository
.SH OPTIONS
.TP
\fB\-\-rebase\fR

.TP
\fB\-\-no\-ff\fR

.TP
\fB\-\-squash\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIREMOTE\fR]
Remote name (uses tracking if not specified)
.TP
[\fIBRANCH\fR]
Branch to pull (uses current branch if not specified)
