.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH commit 1  "commit "
.SH NAME
commit \- Record changes to the repository
.SH SYNOPSIS
\fBcommit\fR [\fB\-m\fR|\fB\-\-message\fR] [\fB\-a\fR|\fB\-\-all\fR] [\fB\-\-amend\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
Record changes to the repository
.SH OPTIONS
.TP
\fB\-m\fR, \fB\-\-message\fR \fI<MESSAGE>\fR

.TP
\fB\-a\fR, \fB\-\-all\fR

.TP
\fB\-\-amend\fR
Amend the previous commit
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
