.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH push 1  "push "
.SH NAME
push \- Update remote refs along with associated objects
.SH SYNOPSIS
\fBpush\fR [\fB\-f\fR|\fB\-\-force\fR] [\fB\-\-force\-with\-lease\fR] [\fB\-\-dry\-run\fR] [\fB\-\-tags\fR] [\fB\-u\fR|\fB\-\-set\-upstream\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIREMOTE\fR] [\fIBRANCH\fR]
.SH DESCRIPTION
Update remote refs along with associated objects
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-force\fR

.TP
\fB\-\-force\-with\-lease\fR

.TP
\fB\-\-dry\-run\fR

.TP
\fB\-\-tags\fR

.TP
\fB\-u\fR, \fB\-\-set\-upstream\fR
Set upstream tracking for the branch
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIREMOTE\fR]
Remote name (uses tracking if not specified)
.TP
[\fIBRANCH\fR]
Branch to push (uses current branch if not specified)
