.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH add 1  "add "
.SH NAME
add \- Add files to be tracked
.SH SYNOPSIS
\fBadd\fR [\fB\-f\fR|\fB\-\-force\fR] [\fB\-A\fR|\fB\-\-all\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATHS\fR]
.SH DESCRIPTION
Add files to be tracked
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-force\fR

.TP
\fB\-A\fR, \fB\-\-all\fR
Stage all changes (modified, deleted, and new files)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATHS\fR]
Paths to add
