.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH merge 1  "merge "
.SH NAME
merge \- Join two or more development histories together
.SH SYNOPSIS
\fBmerge\fR [\fB\-\-no\-ff\fR] [\fB\-\-squash\fR] [\fB\-m\fR|\fB\-\-message\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIBRANCH\fR>
.SH DESCRIPTION
Join two or more development histories together
.SH OPTIONS
.TP
\fB\-\-no\-ff\fR

.TP
\fB\-\-squash\fR

.TP
\fB\-m\fR, \fB\-\-message\fR \fI<MESSAGE>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIBRANCH\fR>
Branch or commit to merge
