.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH status 1  "status "
.SH NAME
status \- Show the working tree status
.SH SYNOPSIS
\fBstatus\fR [\fB\-s\fR|\fB\-\-short\fR] [\fB\-u\fR|\fB\-\-untracked\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
Show the working tree status
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-short\fR

.TP
\fB\-u\fR, \fB\-\-untracked\fR \fI<UNTRACKED>\fR [default: true]
Show untracked files (default: true, use \-\-no\-untracked to disable)
.br

.br
[\fIpossible values: \fRtrue, false]
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
