Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        Option "TapButton1" "1"
        Option "HorizScrollDelta" "-111"
        Option "VertScrollDelta" "-111"
	MatchDevicePath "/dev/input/event*"
        Driver "libinput"
EndSection
