# Codecov configuration for dotman-rs
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  # Coverage display settings
  range: 70..100    # Color range for coverage percentage
  round: down       # Round coverage down
  precision: 2      # Two decimal places for coverage
  
  status:
    # Overall project coverage requirements
    project:
      default:
        target: 75%         # Target 75% overall coverage
        threshold: 2%       # Allow 2% coverage drop
        base: auto         # Compare against base automatically
        if_ci_failed: error # Fail if CI fails
        
    # Coverage requirements for new/modified code
    patch:
      default:
        target: 80%         # New code should have 80% coverage
        threshold: 0%       # No tolerance for drops in patch coverage
        base: auto
        
# Files and directories to ignore in coverage reports
ignore:
  - "tests/**"              # Test files
  - "benches/**"            # Benchmark files  
  - "examples/**"           # Example code
  - "target/**"             # Build artifacts
  - "**/*.proptest-regressions" # Property test regression files
  - "scripts/**"            # Build scripts
  - "packaging/**"          # Packaging configurations
  - "containers/**"         # Docker configurations
  - "completions/**"        # Shell completions
  - "install/**"            # Installation scripts
  
# Pull request comment configuration
comment:
  layout: "reach, diff, flags, files"  # What to show in PR comments
  behavior: default                     # Update comment on new commits
  require_changes: false                # Comment even if no coverage change
  require_base: false                   # Don't require base coverage
  require_head: true                    # Require head coverage