Section "Screen"
  Identifier "Screen0"
  Device "Intel" 
  Monitor "eDP1"
  DefaultDepth 24
EndSection

Section "Screen"
  Identifier "Screen1"
  Device "Nvidia" 
  Monitor "HDMI-0-1"
  DefaultDepth 24
EndSection

Section "Monitor"
    Identifier  "eDP1"
    Option      "Primary" "true"
EndSection

Section "Monitor"
    Identifier  "HDMI-0-1"
    Option      "LeftOf"  "eDP-1"
    Option      "DPMS"    "true"
EndSection
