Section "InputClass"
        Identifier "libinput touchpad catchall"
        Driver "libinput"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Option "Tapping" "True"
        Option "TappingDrag" "True"
        Option "ScrollMethod" "twofinger"
        Option "AccelProfile" "adaptive"
        Option "AccelSpeed" "0.7"
	Option "NaturalScrolling" "False"
        Option "DisableWhileTyping" "False"
EndSection
