#!/usr/bin/env bash

autorandr -c

# Polkit agent
lxpolkit &

# make keyboard smooth
xset r rate 250 100

# Set the background
ps ax back4.sh | awk '{print $1}' | xargs kill

# back4.sh auto ~/.config/leftwm/wallpaper.gif &

#feh --fullscreen --bg-scale ~/.config/leftwm/grave-of-the-fireflies.jpg

while true; do
	for f in ~/Pictures/wallpapers/*; do
		feh -z --bg-scale --no-fehbg "$f"
		sleep 100
	done
done
# feh --recursive --randomize --bg-fill --slideshow-delay 60 ~/Pictures/wallpapers/
