#!/usr/bin/env bash

autorandr -c

# Polkit agent
lxpolkit &

# make keyboard smooth
xset r rate 250 100

# Set the background
# ps ax back4.sh | awk '{print $1}' | xargs kill

# back4.sh auto ~/.config/leftwm/wallpaper.gif &

#feh --fullscreen --bg-scale ~/.config/leftwm/grave-of-the-fireflies.jpg
