# source = /home/utsav/.cache/wal/colors-hyprland.conf

$background = rgba(20, 22, 24, 0.75)
$foreground = rgba(235, 219, 178, 0.7)
$fail-color = rgba(204, 36, 29, 0.7)
$check-color = rgba(215, 153, 33, 0.7)

# BACKGROUND
background {
    monitor =
    path = ~/Pictures/wallpapers/Colors.png
    blur_passes = 4
    contrast = 2.4
    brightness = 0.85
    vibrancy = 0.4
    vibrancy_darkness = 0.7
}

# GENERAL
general {
    no_fade_in = false
    no_fade_out = false
    hide_cursor = false
    grace = 0
    disable_loading_bar = false
}

# INPUT FIELD
input-field {
	monitor =
	size = 160, 32
	outline_thickness = 2
	dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
	dots_spacing = 0.55G# Scale of dots' absolute size, 0.0 - 1.0
	dots_center = true
	outer_color = $background
	inner_color = $background
	font_color = $foreground
	font_size = 14
	fade_on_empty = false
	rounding = 16
	fail_color = $fail-color
	check_color = $check-color
	placeholder_text = |
	hide_input = false
	position = 0, -210
	halign = center
	valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = $foreground
  font_size = 24
  font_family = JetBrainsMono NFP ExtraBold
  position = 0, 200
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%-H:%M")"
  color = $foreground
  font_size = 84
  font_family = JetBrainsMono NFP ExtraBold
  position = 0, 100
  halign = center
  valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/lockscreen-status.sh whoami)" 
    color = $foreground
    font_size = 14  
    font_family = JetBrainsMono Nerd Font
    position = 0, -150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:5000] echo "$(~/.config/hypr/scripts/lockscreen-status.sh network)"
    color = $foreground
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 24, -16
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/lockscreen-status.sh battery)"
    color = $foreground
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = -24, -16
    halign = right
    valign = top
}


label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/lockscreen-status.sh song)" 
    color = $foreground
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    color = $foreground
    position = 0, 50
    halign = center
    valign = bottom
}
