[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#585B70" # surface2
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#A6ADC8" # subtext0

[colors.cursor]
cursor = "0xd5c4a1"
text = "0x1d2021"

[colors.normal]
black = "#45475A" # surface1
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#BAC2DE" # subtext

[colors.dim]
black = "#45475A" # surface1
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#BAC2DE" # subtext1

[colors.primary]
background = "0x1d2021"
foreground = "0xd5c4a1"

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
startup_mode = "windowed"
opacity = 0.8

[window.dimensions]
columns = 140
lines = 38

