#!/usr/bin/env bash

selected=$(echo "Shutdown Restart" | rofi -dmenu -p "Power Options")

if [ "$selected" == "Shutdown" ]; then
	systemctl poweroff
elif [ "$selected" == "Restart" ]; then
	systemctl reboot
else
	exit 1
fi
